/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageAbout {
    }
    interface PageActivity {
    }
    interface PageCovid {
    }
    interface PageDonate {
    }
    interface PageHome {
    }
    interface PageOnDemand {
    }
    interface PagePartners {
    }
    interface PagePress {
    }
    interface PagePrivacy {
    }
    interface PageReport {
    }
    interface PageTrucks {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {
    }
    var HTMLPageAboutElement: {
        prototype: HTMLPageAboutElement;
        new (): HTMLPageAboutElement;
    };
    interface HTMLPageActivityElement extends Components.PageActivity, HTMLStencilElement {
    }
    var HTMLPageActivityElement: {
        prototype: HTMLPageActivityElement;
        new (): HTMLPageActivityElement;
    };
    interface HTMLPageCovidElement extends Components.PageCovid, HTMLStencilElement {
    }
    var HTMLPageCovidElement: {
        prototype: HTMLPageCovidElement;
        new (): HTMLPageCovidElement;
    };
    interface HTMLPageDonateElement extends Components.PageDonate, HTMLStencilElement {
    }
    var HTMLPageDonateElement: {
        prototype: HTMLPageDonateElement;
        new (): HTMLPageDonateElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageOnDemandElement extends Components.PageOnDemand, HTMLStencilElement {
    }
    var HTMLPageOnDemandElement: {
        prototype: HTMLPageOnDemandElement;
        new (): HTMLPageOnDemandElement;
    };
    interface HTMLPagePartnersElement extends Components.PagePartners, HTMLStencilElement {
    }
    var HTMLPagePartnersElement: {
        prototype: HTMLPagePartnersElement;
        new (): HTMLPagePartnersElement;
    };
    interface HTMLPagePressElement extends Components.PagePress, HTMLStencilElement {
    }
    var HTMLPagePressElement: {
        prototype: HTMLPagePressElement;
        new (): HTMLPagePressElement;
    };
    interface HTMLPagePrivacyElement extends Components.PagePrivacy, HTMLStencilElement {
    }
    var HTMLPagePrivacyElement: {
        prototype: HTMLPagePrivacyElement;
        new (): HTMLPagePrivacyElement;
    };
    interface HTMLPageReportElement extends Components.PageReport, HTMLStencilElement {
    }
    var HTMLPageReportElement: {
        prototype: HTMLPageReportElement;
        new (): HTMLPageReportElement;
    };
    interface HTMLPageTrucksElement extends Components.PageTrucks, HTMLStencilElement {
    }
    var HTMLPageTrucksElement: {
        prototype: HTMLPageTrucksElement;
        new (): HTMLPageTrucksElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-about": HTMLPageAboutElement;
        "page-activity": HTMLPageActivityElement;
        "page-covid": HTMLPageCovidElement;
        "page-donate": HTMLPageDonateElement;
        "page-home": HTMLPageHomeElement;
        "page-on-demand": HTMLPageOnDemandElement;
        "page-partners": HTMLPagePartnersElement;
        "page-press": HTMLPagePressElement;
        "page-privacy": HTMLPagePrivacyElement;
        "page-report": HTMLPageReportElement;
        "page-trucks": HTMLPageTrucksElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageAbout {
    }
    interface PageActivity {
    }
    interface PageCovid {
    }
    interface PageDonate {
    }
    interface PageHome {
    }
    interface PageOnDemand {
    }
    interface PagePartners {
    }
    interface PagePress {
    }
    interface PagePrivacy {
    }
    interface PageReport {
    }
    interface PageTrucks {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-about": PageAbout;
        "page-activity": PageActivity;
        "page-covid": PageCovid;
        "page-donate": PageDonate;
        "page-home": PageHome;
        "page-on-demand": PageOnDemand;
        "page-partners": PagePartners;
        "page-press": PagePress;
        "page-privacy": PagePrivacy;
        "page-report": PageReport;
        "page-trucks": PageTrucks;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-about": LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
            "page-activity": LocalJSX.PageActivity & JSXBase.HTMLAttributes<HTMLPageActivityElement>;
            "page-covid": LocalJSX.PageCovid & JSXBase.HTMLAttributes<HTMLPageCovidElement>;
            "page-donate": LocalJSX.PageDonate & JSXBase.HTMLAttributes<HTMLPageDonateElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-on-demand": LocalJSX.PageOnDemand & JSXBase.HTMLAttributes<HTMLPageOnDemandElement>;
            "page-partners": LocalJSX.PagePartners & JSXBase.HTMLAttributes<HTMLPagePartnersElement>;
            "page-press": LocalJSX.PagePress & JSXBase.HTMLAttributes<HTMLPagePressElement>;
            "page-privacy": LocalJSX.PagePrivacy & JSXBase.HTMLAttributes<HTMLPagePrivacyElement>;
            "page-report": LocalJSX.PageReport & JSXBase.HTMLAttributes<HTMLPageReportElement>;
            "page-trucks": LocalJSX.PageTrucks & JSXBase.HTMLAttributes<HTMLPageTrucksElement>;
        }
    }
}
