/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface AppRoot {}
  interface PageAbout {}
  interface PageActivity {}
  interface PageCovid {}
  interface PageHome {}
  interface PageOnDemand {}
  interface PagePartners {}
  interface PagePress {}
  interface PageTrucks {}
}
declare global {
  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {}
  var HTMLPageAboutElement: {
    prototype: HTMLPageAboutElement;
    new (): HTMLPageAboutElement;
  };
  interface HTMLPageActivityElement extends Components.PageActivity, HTMLStencilElement {}
  var HTMLPageActivityElement: {
    prototype: HTMLPageActivityElement;
    new (): HTMLPageActivityElement;
  };
  interface HTMLPageCovidElement extends Components.PageCovid, HTMLStencilElement {}
  var HTMLPageCovidElement: {
    prototype: HTMLPageCovidElement;
    new (): HTMLPageCovidElement;
  };
  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };
  interface HTMLPageOnDemandElement extends Components.PageOnDemand, HTMLStencilElement {}
  var HTMLPageOnDemandElement: {
    prototype: HTMLPageOnDemandElement;
    new (): HTMLPageOnDemandElement;
  };
  interface HTMLPagePartnersElement extends Components.PagePartners, HTMLStencilElement {}
  var HTMLPagePartnersElement: {
    prototype: HTMLPagePartnersElement;
    new (): HTMLPagePartnersElement;
  };
  interface HTMLPagePressElement extends Components.PagePress, HTMLStencilElement {}
  var HTMLPagePressElement: {
    prototype: HTMLPagePressElement;
    new (): HTMLPagePressElement;
  };
  interface HTMLPageTrucksElement extends Components.PageTrucks, HTMLStencilElement {}
  var HTMLPageTrucksElement: {
    prototype: HTMLPageTrucksElement;
    new (): HTMLPageTrucksElement;
  };
  interface HTMLElementTagNameMap {
    "app-root": HTMLAppRootElement;
    "page-about": HTMLPageAboutElement;
    "page-activity": HTMLPageActivityElement;
    "page-covid": HTMLPageCovidElement;
    "page-home": HTMLPageHomeElement;
    "page-on-demand": HTMLPageOnDemandElement;
    "page-partners": HTMLPagePartnersElement;
    "page-press": HTMLPagePressElement;
    "page-trucks": HTMLPageTrucksElement;
  }
}
declare namespace LocalJSX {
  interface AppRoot {}
  interface PageAbout {}
  interface PageActivity {}
  interface PageCovid {}
  interface PageHome {}
  interface PageOnDemand {}
  interface PagePartners {}
  interface PagePress {}
  interface PageTrucks {}
  interface IntrinsicElements {
    "app-root": AppRoot;
    "page-about": PageAbout;
    "page-activity": PageActivity;
    "page-covid": PageCovid;
    "page-home": PageHome;
    "page-on-demand": PageOnDemand;
    "page-partners": PagePartners;
    "page-press": PagePress;
    "page-trucks": PageTrucks;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      "page-about": LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
      "page-activity": LocalJSX.PageActivity & JSXBase.HTMLAttributes<HTMLPageActivityElement>;
      "page-covid": LocalJSX.PageCovid & JSXBase.HTMLAttributes<HTMLPageCovidElement>;
      "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
      "page-on-demand": LocalJSX.PageOnDemand & JSXBase.HTMLAttributes<HTMLPageOnDemandElement>;
      "page-partners": LocalJSX.PagePartners & JSXBase.HTMLAttributes<HTMLPagePartnersElement>;
      "page-press": LocalJSX.PagePress & JSXBase.HTMLAttributes<HTMLPagePressElement>;
      "page-trucks": LocalJSX.PageTrucks & JSXBase.HTMLAttributes<HTMLPageTrucksElement>;
    }
  }
}
