name: Test

on:
  push:
    branches-ignore: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12

      - name: npm install dependencies
        run: npm install

      - name: run prettier
        run: npm run prettier

      - name: run tslint
        run: npm run lint

      - name: run tests
        run: npm run test
